In [1]:
import pandas as pd

In [2]:
elig = pd.read_csv("../Data/Raw/eligibility_processing.csv")

In [3]:
md_elig = elig[elig["State Name"] == "Maryland"].copy()

In [4]:
md_elig["priority"] = md_elig["Original or Updated"].map({"O": 0, "U": 1})

md_elig = (
    md_elig
    .sort_values(["Reporting Period", "priority"])
    .drop_duplicates("Reporting Period", keep="last")
    .drop(columns="priority")
)

In [5]:
md_elig = md_elig[
    [
        "Reporting Period",
        "Original or Updated",
        "Beneficiaries with a Renewal Due",
        "Beneficiaries Whose Coverage Was Renewed (Total)",
        "Beneficiaries Disenrolled at Renewal (Total)",
        "Beneficiaries Determined Ineligible at Renewal",
        "Beneficiaries Disenrolled for Procedural Reasons at Renewal",
        "Beneficiaries with a Pending Renewal"
    ]
].dropna().copy()

In [6]:
md_elig["Month"] = pd.to_datetime(
    md_elig["Reporting Period"].astype(str),
    format="%Y%m"
)

md_elig.to_csv(
    "../Data/Processed/eligibility_processing_clean.csv",
    index=False
)

In [7]:
md_elig.head()

,Reporting Period,Original or Updated,Beneficiaries with a Renewal Due,Beneficiaries Whose Coverage Was Renewed (Total),Beneficiaries Disenrolled at Renewal (Total),Beneficiaries Determined Ineligible at Renewal,Beneficiaries Disenrolled for Procedural Reasons at Renewal,Beneficiaries with a Pending Renewal,Month
1445,202305,U,117098.0,80317.0,35370.0,10727.0,24643.0,1411.0,2023-05-01
1447,202306,U,137459.0,105117.0,29560.0,12485.0,17075.0,2782.0,2023-06-01
1449,202307,U,145496.0,102137.0,39278.0,15657.0,23621.0,4081.0,2023-07-01
1451,202308,U,115313.0,98163.0,12569.0,12569.0,0.0,4581.0,2023-08-01
1453,202309,U,115491.0,95968.0,13529.0,13529.0,0.0,5994.0,2023-09-01

In [8]:
md_elig[
    ["Reporting Period", "Original or Updated", "Month"]
].tail(10)

      Reporting Period Original or Updated      Month
1497            202507                   U 2025-07-01
1499            202508                   U 2025-08-01
1501            202509                   U 2025-09-01
1503            202510                   U 2025-10-01
1505            202511                   U 2025-11-01
1507            202512                   U 2025-12-01
1508            202601                   O 2026-01-01
1509            202602                   O 2026-02-01
1510            202603                   O 2026-03-01
1511            202604                   O 2026-04-01

In [9]:
md_elig.to_csv(
    "../Data/Processed/eligibility_processing_clean.csv",
    index=False
)